/**
 * Red Dust County — nine cinematic stand-offs.
 * Coordinates are virtual 720×1280. Player muzzle sits at (360, 1172).
 *
 * preview: "full" | "first" | "deadeye"
 * Enemies may peek, pace, or hide. Pans may swing.
 */
(function (root) {
  const GW = (root.GW = root.GW || {});

  GW.LEVELS = [
    {
      id: "high-draw",
      chapter: "RED DUST COUNTY",
      numeral: "I",
      name: "HIGH DRAW",
      bg: "street",
      hint: "No skillet. Hold. Put the thread on him. Let go first.",
      par: 1,
      preview: "full",
      entities: [
        { type: "enemy", x: 360, y: 430, species: "outlaw", draw: 6.6 },
      ],
    },
    {
      id: "hanging-pan",
      chapter: "RED DUST COUNTY",
      numeral: "II",
      name: "THE HANGING PAN",
      bg: "street",
      hint: "The skillet swings. Catch it at the end of the gold thread.",
      par: 1,
      preview: "full",
      entities: [
        { type: "crate", x: 360, y: 820, s: 1.15 },
        { type: "pan", x: 600, y: 520, s: 1.15, swing: 48, period: 3.4 },
        { type: "enemy", x: 360, y: 400, species: "outlaw", draw: 8.2 },
      ],
    },
    {
      id: "iron-hoops",
      chapter: "RED DUST COUNTY",
      numeral: "III",
      name: "IRON HOOPS",
      bg: "street",
      hint: "They duck. The thread dies after the first bounce.",
      par: 2,
      preview: "first",
      entities: [
        { type: "fence", x0: 250, x1: 470, y: 760 },
        { type: "barrel", x: 100, y: 640, s: 1.12 },
        { type: "barrel", x: 630, y: 620, s: 1.12 },
        {
          type: "enemy",
          x: 250,
          y: 400,
          species: "outlaw",
          draw: 7.4,
          peek: true,
          coverX: 250,
          coverY: 690,
        },
        {
          type: "enemy",
          x: 510,
          y: 390,
          species: "outlaw",
          draw: 7.8,
          peek: true,
          coverX: 510,
          coverY: 690,
          peekOff: 0.7,
        },
      ],
    },
    {
      id: "saloon-glass",
      chapter: "THE DRY WELL",
      numeral: "IV",
      name: "SALOON GLASS",
      bg: "saloon",
      hint: "Bank the tin. One slug can kiss two men.",
      par: 2,
      preview: "first",
      entities: [
        { type: "fence", x0: 250, x1: 470, y: 780 },
        { type: "sign", x: 610, y: 600, h: 200 },
        { type: "pan", x: 100, y: 640, s: 1, swing: 36, period: 3.0 },
        { type: "enemy", x: 360, y: 400, species: "sharp", draw: 6.6 },
        { type: "enemy", x: 240, y: 380, species: "outlaw", draw: 7.4 },
      ],
    },
    {
      id: "street-sweep",
      chapter: "THE DRY WELL",
      numeral: "V",
      name: "STREET SWEEP",
      bg: "street",
      hint: "Three men walking. Lead the one on the boardwalk.",
      par: 3,
      preview: "first",
      entities: [
        { type: "fence", x0: 240, x1: 480, y: 800 },
        { type: "barrel", x: 360, y: 640, s: 1.05 },
        { type: "pan", x: 640, y: 620, s: 1 },
        { type: "sign", x: 80, y: 620, h: 210 },
        {
          type: "enemy",
          x: 220,
          y: 390,
          species: "outlaw",
          draw: 7.0,
          pace: true,
          x0: 170,
          x1: 280,
          paceSp: 28,
        },
        { type: "enemy", x: 360, y: 340, species: "sharp", draw: 6.4 },
        {
          type: "enemy",
          x: 520,
          y: 390,
          species: "outlaw",
          draw: 7.2,
          peek: true,
          coverX: 520,
          coverY: 700,
        },
      ],
    },
    {
      id: "the-star",
      chapter: "BADGE AND BONE",
      numeral: "VI",
      name: "THE STAR",
      bg: "gallows",
      hint: "Deadeye. No thread. The marshal takes two — or one through the hat.",
      par: 2,
      preview: "deadeye",
      entities: [
        { type: "crate", x: 360, y: 790, s: 1.2 },
        { type: "crate", x: 250, y: 700, s: 0.85 },
        { type: "pan", x: 575, y: 610, s: 1, swing: 40, period: 3.6 },
        { type: "sign", x: 140, y: 560, h: 220 },
        {
          type: "enemy",
          x: 370,
          y: 400,
          species: "marshal",
          draw: 8.4,
          hp: 2,
          peek: true,
          coverX: 300,
          coverY: 680,
        },
      ],
    },
    {
      id: "canyon-cross",
      chapter: "BADGE AND BONE",
      numeral: "VII",
      name: "CANYON CROSS",
      bg: "canyon",
      hint: "Rock swallows slugs. Time the skillet.",
      par: 3,
      preview: "deadeye",
      entities: [
        { type: "fence", x0: 230, x1: 490, y: 790 },
        { type: "barrel", x: 360, y: 660, s: 1.05 },
        { type: "pan", x: 110, y: 620, s: 0.95, swing: 44, period: 2.8 },
        { type: "sign", x: 630, y: 600, h: 200 },
        {
          type: "enemy",
          x: 200,
          y: 400,
          species: "outlaw",
          draw: 6.8,
          peek: true,
          coverX: 200,
          coverY: 700,
        },
        {
          type: "enemy",
          x: 360,
          y: 340,
          species: "sharp",
          draw: 6.1,
          pace: true,
          x0: 300,
          x1: 430,
          paceSp: 24,
        },
        { type: "enemy", x: 540, y: 400, species: "outlaw", draw: 7.0 },
      ],
    },
    {
      id: "iron-horse",
      chapter: "LAST LIGHT",
      numeral: "VIII",
      name: "IRON HORSE",
      bg: "depot",
      hint: "Two bounces is a prayer. Three is a story.",
      par: 3,
      preview: "deadeye",
      entities: [
        { type: "crate", x: 360, y: 800, s: 1.1 },
        { type: "barrel", x: 200, y: 680, s: 1 },
        { type: "barrel", x: 540, y: 650, s: 1 },
        { type: "pan", x: 120, y: 520, s: 0.95, swing: 38, period: 3.1 },
        { type: "sign", x: 620, y: 500, h: 230 },
        { type: "enemy", x: 220, y: 380, species: "sharp", draw: 6.2 },
        {
          type: "enemy",
          x: 500,
          y: 360,
          species: "outlaw",
          draw: 6.6,
          peek: true,
          coverX: 500,
          coverY: 680,
        },
        { type: "enemy", x: 360, y: 300, species: "marshal", draw: 7.6, hp: 2 },
      ],
    },
    {
      id: "high-noon",
      chapter: "LAST LIGHT",
      numeral: "IX",
      name: "HIGH NOON",
      bg: "gallows",
      hint: "The whole county came. Empty the cylinder.",
      par: 4,
      preview: "deadeye",
      entities: [
        { type: "crate", x: 260, y: 780, s: 1 },
        { type: "crate", x: 480, y: 760, s: 1 },
        { type: "barrel", x: 140, y: 690, s: 0.95 },
        { type: "barrel", x: 600, y: 670, s: 0.95 },
        { type: "pan", x: 360, y: 620, s: 1.05, swing: 50, period: 2.9 },
        { type: "sign", x: 80, y: 530, h: 200 },
        { type: "sign", x: 650, y: 510, h: 210 },
        {
          type: "enemy",
          x: 200,
          y: 400,
          species: "outlaw",
          draw: 6.4,
          peek: true,
          coverX: 200,
          coverY: 700,
        },
        { type: "enemy", x: 360, y: 330, species: "marshal", draw: 7.2, hp: 2 },
        {
          type: "enemy",
          x: 530,
          y: 390,
          species: "sharp",
          draw: 5.9,
          pace: true,
          x0: 480,
          x1: 580,
          paceSp: 26,
        },
        { type: "enemy", x: 360, y: 470, species: "outlaw", draw: 7.0 },
      ],
    },
  ];
})(typeof window !== "undefined" ? window : globalThis);
